@startuml attackMoveCommand

start

if (attack command?) then (yes)
	:run attack command;
	if (Attack command is done?) then (yes)
	else (no)
		if (Should stop attacking?) then (yes)
		else (no)
			#pink:return false;
			stop
		endif
	endif
	#palegreen:add Steppable remove attack command;
else (no)

	if (Look for new target?) then (yes)
		#palegreen:add Steppable store current position;
		#palegreen:add Steppable to add attack command;
		#pink:return false;
		stop
	else (no)
endif

endif

:run move command;

if (move command is done?) then (yes)
	#pink:return true;
else (no)
	#pink:return false;
endif

stop

@enduml
