#ifndef __StepUpgradeGenerator__
#define __StepUpgradeGenerator__

#include <vector>

namespace octopus
{
class Steppable;

/// @brief this simple class represents an steppable generator upgrade
/// An upgrade can be researched in a building
/// The upgrade level step should not be generated by this generator
class StepUpgradeGenerator
{
public:
    virtual ~StepUpgradeGenerator() {}

    /// @brief Create a new copy of this generator
    /// this is required to ease up memory handling between steps and states for options handling
    /// @return a newly created copy of this genertor
    virtual StepUpgradeGenerator* newCopy() const = 0;

    /// @brief get internal steppable for the given option
    /// @param options_p the option index
    /// @return a vector of steppables (owner is given away)
    virtual std::vector<Steppable *> getSteppables(unsigned long player_p) const = 0;
};

} // namespace octopus


#endif
